[pytest]
# Custom markers to categorize tests
markers =
    all: all tests
    unit: unit tests
    nonregression: non-regression tests

# Additional pytest configurations can be added here
testpaths = tests               # Default location of tests